<?php
// $Id$

require_once('imageapi_gd.inc');

/**
 * Implementation of hook_imagecache_actions().
 */
function smartcrop_imagecache_actions() {
  $actions = array(
    'smartcrop_scale_and_crop' => array(
      'name' => 'Smart Crop',
      'description' => 'Resize an image while maintaining aspect ratio, then crop based entropy.',
      'file' => 'smartcrop_actions.inc',
    ),
  );
  return $actions;
}