<?php
// $Id$

require_once('imageapi_gd.inc');
require_once('smartcrop.effects.inc');

/**
 * Implements hook_theme().
 */
function smartcrop_theme() {
  $theme = array(
    'smartcrop_scale_and_crop' => array(
      'file' => 'smartcrop_actions.inc',
      'render element' => array('element' => NULL),
    ),
    'smartcrop_crop' => array(
      'file' => 'smartcrop_actions.inc',
      'render element' => array('element' => NULL),
    ),
  );
  return $theme;
}
